/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pokeswing.principal;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phana
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Fournisseur
     */
    public Client() {
        initComponents();
        this.setTitle("Pokepok gestion des clients");
        setLocationRelativeTo(null);
        tableUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNOM = new javax.swing.JTextField();
        txtPRENOM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtADRESSE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCODEPOSTAL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVILLE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPAYS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTELEPHONE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEMAIL = new javax.swing.JTextField();
        boutton = new javax.swing.JPanel();
        btnAjouterC = new javax.swing.JButton();
        btnModifierC = new javax.swing.JButton();
        btnSupprimerC = new javax.swing.JButton();
        tableau = new javax.swing.JScrollPane();
        tabCLIENT = new javax.swing.JTable();
        btnRetour = new javax.swing.JButton();
        titre = new javax.swing.JPanel();
        label_titre = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(1920, 1280));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setBackground(new java.awt.Color(255, 255, 255, 100));
        main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 5));

        info.setBackground(new java.awt.Color(255, 255, 255, 130));
        info.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2), "Information Client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Nom :");

        txtNOM.setForeground(new java.awt.Color(0, 102, 51));

        txtPRENOM.setForeground(new java.awt.Color(0, 102, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Prénom :");

        txtADRESSE.setForeground(new java.awt.Color(0, 102, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Adresse :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Code Postal :");

        txtCODEPOSTAL.setForeground(new java.awt.Color(0, 102, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setText("Ville :");

        txtVILLE.setForeground(new java.awt.Color(0, 102, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText("Pays :");

        txtPAYS.setForeground(new java.awt.Color(0, 102, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Téléphone :");

        txtTELEPHONE.setForeground(new java.awt.Color(0, 102, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setText("Email :");

        txtEMAIL.setForeground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNOM, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPRENOM))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtADRESSE))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCODEPOSTAL))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVILLE))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPAYS))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTELEPHONE)
                            .addGroup(infoLayout.createSequentialGroup()
                                .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPRENOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtADRESSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCODEPOSTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVILLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPAYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTELEPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boutton.setBackground(new java.awt.Color(0, 0, 0, 0));

        btnAjouterC.setBackground(new java.awt.Color(0, 102, 0));
        btnAjouterC.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouterC.setText("Ajouter");
        btnAjouterC.setBorderPainted(false);
        btnAjouterC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterCActionPerformed(evt);
            }
        });

        btnModifierC.setBackground(new java.awt.Color(0, 102, 0));
        btnModifierC.setForeground(new java.awt.Color(255, 255, 255));
        btnModifierC.setText("Modifier");
        btnModifierC.setBorderPainted(false);
        btnModifierC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierCActionPerformed(evt);
            }
        });

        btnSupprimerC.setBackground(new java.awt.Color(0, 102, 0));
        btnSupprimerC.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimerC.setText("Supprimer");
        btnSupprimerC.setBorderPainted(false);
        btnSupprimerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bouttonLayout = new javax.swing.GroupLayout(boutton);
        boutton.setLayout(bouttonLayout);
        bouttonLayout.setHorizontalGroup(
            bouttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bouttonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnAjouterC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnModifierC)
                .addGap(102, 102, 102)
                .addComponent(btnSupprimerC)
                .addGap(41, 41, 41))
        );
        bouttonLayout.setVerticalGroup(
            bouttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bouttonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bouttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterC)
                    .addComponent(btnModifierC)
                    .addComponent(btnSupprimerC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabCLIENT.setForeground(new java.awt.Color(0, 102, 51));
        tabCLIENT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID CLient", "Nom", "Prenom", "Adresse", "Code Postal", "Ville", "Pays", "Téléphone", "Email"
            }
        ));
        tabCLIENT.setFocusable(false);
        tabCLIENT.setGridColor(new java.awt.Color(204, 255, 255));
        tabCLIENT.setRequestFocusEnabled(false);
        tabCLIENT.setSelectionBackground(new java.awt.Color(0, 102, 51));
        tabCLIENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCLIENTMouseClicked(evt);
            }
        });
        tableau.setViewportView(tabCLIENT);

        btnRetour.setBackground(new java.awt.Color(0, 102, 51));
        btnRetour.setForeground(new java.awt.Color(255, 255, 255));
        btnRetour.setText("Retour");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });

        titre.setBackground(new java.awt.Color(255, 255, 255));

        label_titre.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        label_titre.setForeground(new java.awt.Color(0, 153, 51));
        label_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titre.setText("LISTE DES CLIENTS");

        javax.swing.GroupLayout titreLayout = new javax.swing.GroupLayout(titre);
        titre.setLayout(titreLayout);
        titreLayout.setHorizontalGroup(
            titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titreLayout.createSequentialGroup()
                .addComponent(label_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 655, Short.MAX_VALUE))
        );
        titreLayout.setVerticalGroup(
            titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_titre, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tableau, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(586, 586, 586)
                        .addComponent(btnRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(boutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableau, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRetour)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 1280, 740));

        logo.setBackground(new java.awt.Color(51, 102, 255));
        logo.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        logo.setForeground(new java.awt.Color(0, 102, 51));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\phana\\Documents\\com.PokeSwing_jar_1.0-SNAPSHOT\\logo.png")); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1950, 250));

        fond.setForeground(new java.awt.Color(153, 0, 0));
        fond.setIcon(new javax.swing.ImageIcon("C:\\Users\\phana\\Documents\\com.PokeSwing_jar_1.0-SNAPSHOT\\FondEcranPoke1.png")); // NOI18N
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection con; // déclaratioon de connection 
    PreparedStatement pst; 
    
    private void tableUpdate(){
            int cpt;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/pokedb", "root","prout_KK1987"); // Demande au DriverManager (gestionnaire de manager) de récupérer et de stocker les infos dans la variable con
                    pst = con.prepareStatement("SELECT * FROM clients");
                    ResultSet rs = pst.executeQuery();
                    ResultSetMetaData rsmd = rs.getMetaData();
                    cpt = rsmd.getColumnCount();
                    DefaultTableModel dtm = (DefaultTableModel) tabCLIENT.getModel();
                    dtm.setRowCount(0);
                    
                    while(rs.next()){
                        Vector  vect = new Vector();
                        
                        for(int i = 1; i <= cpt; i++){
                            vect.add(rs.getString("IDCLIENT"));
                            vect.add(rs.getString("NOM"));
                            vect.add(rs.getString("PRENOM"));
                            vect.add(rs.getString("ADRESSE"));
                            vect.add(rs.getString("CODEPOSTAL"));
                            vect.add(rs.getString("VILLE"));
                            vect.add(rs.getString("PAYS"));
                            vect.add(rs.getString("TELEPHONE"));
                            vect.add(rs.getString("EMAIL"));
                            
                        }
                    dtm.addRow(vect);
                    }
                            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
    
    private void btnAjouterCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterCActionPerformed
        // Ajout fournisseur via le bouton "ajouter"
        String nom = txtNOM.getText();
        String prenom = txtPRENOM.getText();
        String adresse = txtADRESSE.getText();
        String codePostal = txtCODEPOSTAL.getText();
        String ville = txtVILLE.getText();
        String pays = txtPAYS.getText();
        String telephone = txtTELEPHONE.getText();
        String email = txtEMAIL.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pokedb", "root","prout_KK1987"); // Demande au DriverManager (gestionnaire de manager) de récupérer et de stocker les informations dans la variable con
            pst = con.prepareStatement("INSERT INTO clients(NOM,PRENOM,ADRESSE,CODEPOSTAL,VILLE,PAYS,TELEPHONE,EMAIL) VALUES(?,?,?,?,?,?,?,?)"); //appel du "statement" contenant toutes les informations
            
            pst.setString(1, nom);
            pst.setString(2, prenom);
            pst.setString(3, adresse);
            pst.setString(4, codePostal);
            pst.setString(5, ville);
            pst.setString(6, pays);
            pst.setString(7, telephone);
            pst.setString(8, email);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Données enregistrées"); // pour afficher une fenetre
            
            //Pour vider le contenu des champs après avoir ajouter un objet
            txtNOM.setText("");
            txtPRENOM.setText("");
            txtADRESSE.setText("");
            txtCODEPOSTAL.setText("");
            txtVILLE.setText("");
            txtPAYS.setText("");
            txtTELEPHONE.setText("");
            txtEMAIL.setText("");
            
            tableUpdate();
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAjouterCActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
       
        dispose();
       
        
    }//GEN-LAST:event_btnRetourActionPerformed

    private void btnModifierCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierCActionPerformed
        
        try {
            DefaultTableModel dtm = (DefaultTableModel) tabCLIENT.getModel();
            int selectedIndex = tabCLIENT.getSelectedRow();
            
            int idClient = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString()); // integer.parseInt=> converti le type en entier
            String nom = txtNOM.getText();
            String prenom = txtPRENOM.getText();
            String adresse = txtADRESSE.getText();
            String codepostal = txtCODEPOSTAL.getText();
            String ville = txtVILLE.getText();
            String pays = txtPAYS.getText();
            String telephone = txtTELEPHONE.getText();
            String email = txtEMAIL.getText();
            
            
            Class.forName("com.mysql.cj.jdbc.Driver"); //Enregistre le driver
            con = DriverManager.getConnection("jdbc:mysql://localhost/pokedb", "root","prout_KK1987");
            pst = con.prepareStatement("update clients set NOM=?, PRENOM=?, ADRESSE=?, CODEPOSTAL=?, VILLE=?, PAYS=?, TELEPHONE=?, EMAIL=? where IDCLIENT=?");
            pst.setString(1, nom);
            pst.setString(2, prenom);
            pst.setString(3, adresse);
            pst.setString(4, codepostal);
            pst.setString(5, ville);
            pst.setString(6, pays);
            pst.setString(7, telephone);
            pst.setString(8, email);
            pst.setInt(9, idClient); // attention Int
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Données mise à jour");
            
            txtNOM.setText("");
            txtPRENOM.setText("");
            txtADRESSE.setText("");
            txtCODEPOSTAL.setText("");
            txtVILLE.setText("");
            txtPAYS.setText("");
            txtTELEPHONE.setText("");
            txtEMAIL.setText("");
            
            tableUpdate();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_btnModifierCActionPerformed

    private void tabCLIENTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCLIENTMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) tabCLIENT.getModel();
        int selectedIndex = tabCLIENT.getSelectedRow();
        
        txtNOM.setText(dtm.getValueAt(selectedIndex, 1).toString()); //récupere les données dans dtm, la valeur 1 dans le champs selectionné
        txtPRENOM.setText(dtm.getValueAt(selectedIndex, 2).toString());
        txtADRESSE.setText(dtm.getValueAt(selectedIndex, 3).toString());
        txtCODEPOSTAL.setText(dtm.getValueAt(selectedIndex, 4).toString());
        txtVILLE.setText(dtm.getValueAt(selectedIndex, 5).toString());
        txtPAYS.setText(dtm.getValueAt(selectedIndex, 6).toString());
        txtTELEPHONE.setText(dtm.getValueAt(selectedIndex, 7).toString());
        txtEMAIL.setText(dtm.getValueAt(selectedIndex, 8).toString());
    }//GEN-LAST:event_tabCLIENTMouseClicked

    private void btnSupprimerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerCActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tabCLIENT.getModel();
        int selectedIndex = tabCLIENT.getSelectedRow();
        int idClient = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette données?","Attention",JOptionPane.YES_NO_OPTION);
        
        if(dialogResult == JOptionPane.YES_OPTION ){
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/pokedb", "root","prout_KK1987");
                pst = con.prepareStatement("delete from clients where IDCLIENT=?");
                pst.setInt(1, idClient);
                
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Les données ont été supprimées");
                
                txtNOM.setText("");
                txtPRENOM.setText("");
                txtADRESSE.setText("");
                txtCODEPOSTAL.setText("");
                txtVILLE.setText("");
                txtPAYS.setText("");
                txtTELEPHONE.setText("");
                txtEMAIL.setText("");
                
                tableUpdate();
            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_btnSupprimerCActionPerformed

    
    /**
     * @param args the command line arguments
     */
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boutton;
    private javax.swing.JButton btnAjouterC;
    private javax.swing.JButton btnModifierC;
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnSupprimerC;
    private javax.swing.JLabel fond;
    private javax.swing.JPanel info;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_titre;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel main;
    private javax.swing.JTable tabCLIENT;
    private javax.swing.JScrollPane tableau;
    private javax.swing.JPanel titre;
    private javax.swing.JTextField txtADRESSE;
    private javax.swing.JTextField txtCODEPOSTAL;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtNOM;
    private javax.swing.JTextField txtPAYS;
    private javax.swing.JTextField txtPRENOM;
    private javax.swing.JTextField txtTELEPHONE;
    private javax.swing.JTextField txtVILLE;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnRetour
     */
 
}
