/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pokeswing.principal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phana
 */
public class Commande extends javax.swing.JFrame {

    /**
     * Creates new form Commande
     */
    public Commande() {
        initComponents();
        this.setTitle("Pokepok Commandes Administrateur");
        setLocationRelativeTo(null);
        tableUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtIDCOMMANDE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDATECOMMANDE = new javax.swing.JTextField();
        txtTOTALHT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTVA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTOTALTTC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFRAISPORT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNBARTICLE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        boutton = new javax.swing.JPanel();
        btnAjouterC = new javax.swing.JButton();
        btnSupprimerC = new javax.swing.JButton();
        tableaucommande = new javax.swing.JScrollPane();
        tabCOMMANDE = new javax.swing.JTable();
        titre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRetour = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setBackground(new java.awt.Color(255, 255, 255, 100));
        main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 5));
        main.setEnabled(false);

        info.setBackground(new java.awt.Color(255, 255, 255, 130));
        info.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2), "infos commandes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 51))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setText("ID Commande :");

        txtIDCOMMANDE.setForeground(new java.awt.Color(0, 102, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText("Date Commande : ");

        txtDATECOMMANDE.setForeground(new java.awt.Color(0, 102, 51));

        txtTOTALHT.setForeground(new java.awt.Color(0, 102, 51));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 51));
        jLabel9.setText("TVA : ");

        txtTVA.setForeground(new java.awt.Color(0, 102, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setText("Total TTC :");

        txtTOTALTTC.setForeground(new java.awt.Color(0, 102, 51));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 51));
        jLabel11.setText("Frais de Port :");

        txtFRAISPORT.setForeground(new java.awt.Color(0, 102, 51));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 51));
        jLabel12.setText("Nombre d'article :");

        txtNBARTICLE.setForeground(new java.awt.Color(0, 102, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Total HT :");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(58, 58, 58)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTVA)
                            .addComponent(txtTOTALTTC)
                            .addComponent(txtTOTALHT)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFRAISPORT, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(txtNBARTICLE)
                            .addComponent(txtIDCOMMANDE)
                            .addComponent(txtDATECOMMANDE))))
                .addGap(20, 20, 20))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDCOMMANDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDATECOMMANDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNBARTICLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFRAISPORT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTOTALHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtTOTALTTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );

        boutton.setBackground(new java.awt.Color(0, 0, 0, 0));

        btnAjouterC.setBackground(new java.awt.Color(0, 102, 51));
        btnAjouterC.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouterC.setText(" Ajouter ou modifier");
        btnAjouterC.setBorderPainted(false);
        btnAjouterC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterCActionPerformed(evt);
            }
        });

        btnSupprimerC.setBackground(new java.awt.Color(0, 102, 51));
        btnSupprimerC.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimerC.setText("Supprimer");
        btnSupprimerC.setBorderPainted(false);
        btnSupprimerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bouttonLayout = new javax.swing.GroupLayout(boutton);
        boutton.setLayout(bouttonLayout);
        bouttonLayout.setHorizontalGroup(
            bouttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bouttonLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnAjouterC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(btnSupprimerC)
                .addGap(85, 85, 85))
        );
        bouttonLayout.setVerticalGroup(
            bouttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bouttonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bouttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterC)
                    .addComponent(btnSupprimerC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabCOMMANDE.setForeground(new java.awt.Color(0, 102, 51));
        tabCOMMANDE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Commande", "Date Commande", "Frais de Port", "Nb Article", "TotalHT", "TVA", "TotalTTC", "Nom Client", "Prenom Client"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabCOMMANDE.setGridColor(new java.awt.Color(102, 51, 255));
        tabCOMMANDE.setSelectionBackground(new java.awt.Color(0, 102, 51));
        tabCOMMANDE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCOMMANDEMouseClicked(evt);
            }
        });
        tableaucommande.setViewportView(tabCOMMANDE);
        if (tabCOMMANDE.getColumnModel().getColumnCount() > 0) {
            tabCOMMANDE.getColumnModel().getColumn(3).setMinWidth(0);
            tabCOMMANDE.getColumnModel().getColumn(3).setMaxWidth(0);
            tabCOMMANDE.getColumnModel().getColumn(4).setMinWidth(0);
            tabCOMMANDE.getColumnModel().getColumn(4).setMaxWidth(0);
            tabCOMMANDE.getColumnModel().getColumn(5).setMinWidth(0);
            tabCOMMANDE.getColumnModel().getColumn(5).setMaxWidth(0);
            tabCOMMANDE.getColumnModel().getColumn(6).setMinWidth(0);
            tabCOMMANDE.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        titre.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTE DES COMMANDES");

        javax.swing.GroupLayout titreLayout = new javax.swing.GroupLayout(titre);
        titre.setLayout(titreLayout);
        titreLayout.setHorizontalGroup(
            titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titreLayout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        titreLayout.setVerticalGroup(
            titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        btnRetour.setBackground(new java.awt.Color(0, 102, 51));
        btnRetour.setForeground(new java.awt.Color(255, 255, 255));
        btnRetour.setText("Retour");
        btnRetour.setBorderPainted(false);
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(tableaucommande, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addComponent(btnRetour)))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableaucommande, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnRetour)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 1280, 720));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\phana\\Documents\\com.PokeSwing_jar_1.0-SNAPSHOT\\logo.png")); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 250));

        fond.setIcon(new javax.swing.ImageIcon("C:\\Users\\phana\\Documents\\com.PokeSwing_jar_1.0-SNAPSHOT\\FondEcranPoke1.png")); // NOI18N
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection con; // déclaratioon de connection 
    PreparedStatement pst; 
    
    private void tableUpdate(){
            int cpt;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/pokedb", "root","prout_KK1987"); // Demande au DriverManager (gestionnaire de manager) de récupérer et de stocker les infos dans la variable con
                    pst = con.prepareStatement("SELECT * FROM commandes");
                    ResultSet rs = pst.executeQuery();
                    ResultSetMetaData rsmd = rs.getMetaData();
                    cpt = rsmd.getColumnCount();
                    DefaultTableModel dtm = (DefaultTableModel) tabCOMMANDE.getModel();
                    dtm.setRowCount(0);
                    
                    while(rs.next()){
                        Vector  vect = new Vector();
                        
                        for(int i = 1; i <= cpt; i++){
                            vect.add(rs.getString("IDCMD"));
                            vect.add(rs.getString("DATECMD"));
                            vect.add(rs.getString("FRAISDEPORTCMD"));
                            vect.add(rs.getString("NBARTICLE"));
                            vect.add(rs.getString("TOTALHT"));
                            vect.add(rs.getString("TVA"));
                            vect.add(rs.getString("TOTALTTC"));
                            
                        }
                    dtm.addRow(vect);
                    }
                            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
    
    private void btnAjouterCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterCActionPerformed
     GestionCommande newGcmd = new GestionCommande();
     newGcmd.setVisible(true);
    }//GEN-LAST:event_btnAjouterCActionPerformed

    private void tabCOMMANDEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCOMMANDEMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) tabCOMMANDE.getModel();
        int selectedIndex = tabCOMMANDE.getSelectedRow();
        
        txtIDCOMMANDE.setText(dtm.getValueAt(selectedIndex, 0).toString()); //récupere les données dans dtm, la valeur 1 dans le champs selectionné
        txtDATECOMMANDE.setText(dtm.getValueAt(selectedIndex, 1).toString());
        txtFRAISPORT.setText(dtm.getValueAt(selectedIndex, 2).toString());
        txtNBARTICLE.setText(dtm.getValueAt(selectedIndex, 3).toString());
        txtTOTALHT.setText(dtm.getValueAt(selectedIndex, 4).toString());
        txtTVA.setText(dtm.getValueAt(selectedIndex, 5).toString());
        txtTOTALTTC.setText(dtm.getValueAt(selectedIndex, 6).toString());
    }//GEN-LAST:event_tabCOMMANDEMouseClicked

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        dispose();
    }//GEN-LAST:event_btnRetourActionPerformed

    private void btnSupprimerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerCActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tabCOMMANDE.getModel();
        int selectedIndex = tabCOMMANDE.getSelectedRow();
        int idCommande = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette données?","Attention",JOptionPane.YES_NO_OPTION);
        
        if(dialogResult == JOptionPane.YES_OPTION ){
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/pokedb", "root","prout_KK1987");
                pst = con.prepareStatement("delete from commandes where IDCMD=?");
                pst.setInt(1, idCommande);
                
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Les données ont été supprimées");
                
                txtIDCOMMANDE.setText("");
                txtDATECOMMANDE.setText("");
                txtFRAISPORT.setText("");
                txtNBARTICLE.setText("");
                txtTOTALHT.setText("");
                txtTVA.setText("");
                txtTOTALTTC.setText("");
                
                tableUpdate();
            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSupprimerCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boutton;
    private javax.swing.JButton btnAjouterC;
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnSupprimerC;
    private javax.swing.JLabel fond;
    private javax.swing.JPanel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel main;
    private javax.swing.JTable tabCOMMANDE;
    private javax.swing.JScrollPane tableaucommande;
    private javax.swing.JPanel titre;
    private javax.swing.JTextField txtDATECOMMANDE;
    private javax.swing.JTextField txtFRAISPORT;
    private javax.swing.JTextField txtIDCOMMANDE;
    private javax.swing.JTextField txtNBARTICLE;
    private javax.swing.JTextField txtTOTALHT;
    private javax.swing.JTextField txtTOTALTTC;
    private javax.swing.JTextField txtTVA;
    // End of variables declaration//GEN-END:variables
}
