/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pokeswing.principal;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phana
 */
public class Fournisseur extends javax.swing.JFrame {

    /**
     * Creates new form Fournisseur
     */
    public Fournisseur() {
        initComponents();
        this.setTitle("Pokepoke gestion des fournisseurs Administrateur");
        setLocationRelativeTo(null);
        tableUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRAISONSOCIAL = new javax.swing.JTextField();
        txtNOM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtADRESSE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCODEPOSTAL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVILLE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPAYS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTELEPHONE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFAX = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEMAIL = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAjouterF = new javax.swing.JButton();
        btnModifierF = new javax.swing.JButton();
        btnSupprimerF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabFOURNISSEUR = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRetour = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setBackground(new java.awt.Color(255, 255, 255, 100));
        main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255, 130));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2), "infos fournisseurs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Raison social :");

        txtRAISONSOCIAL.setForeground(new java.awt.Color(0, 102, 51));

        txtNOM.setForeground(new java.awt.Color(0, 102, 51));
        txtNOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Nom :");

        txtADRESSE.setForeground(new java.awt.Color(0, 102, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Adresse :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Code Postal :");

        txtCODEPOSTAL.setForeground(new java.awt.Color(0, 102, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setText("Ville :");

        txtVILLE.setForeground(new java.awt.Color(0, 102, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText("Pays :");

        txtPAYS.setForeground(new java.awt.Color(0, 102, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Téléphone :");

        txtTELEPHONE.setForeground(new java.awt.Color(0, 102, 51));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 51));
        jLabel9.setText("Fax :");

        txtFAX.setForeground(new java.awt.Color(0, 102, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setText("Email :");

        txtEMAIL.setForeground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRAISONSOCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNOM))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtADRESSE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFAX))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEMAIL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCODEPOSTAL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVILLE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPAYS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTELEPHONE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRAISONSOCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtADRESSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCODEPOSTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVILLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPAYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTELEPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255, 130));

        btnAjouterF.setBackground(new java.awt.Color(0, 102, 51));
        btnAjouterF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAjouterF.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouterF.setText("Ajouter");
        btnAjouterF.setBorderPainted(false);
        btnAjouterF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterFActionPerformed(evt);
            }
        });

        btnModifierF.setBackground(new java.awt.Color(0, 102, 51));
        btnModifierF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModifierF.setForeground(new java.awt.Color(255, 255, 255));
        btnModifierF.setText("Modifier");
        btnModifierF.setBorderPainted(false);
        btnModifierF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierFActionPerformed(evt);
            }
        });

        btnSupprimerF.setBackground(new java.awt.Color(0, 102, 51));
        btnSupprimerF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSupprimerF.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimerF.setText("Supprimer");
        btnSupprimerF.setBorderPainted(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjouterF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModifierF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnSupprimerF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifierF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimerF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabFOURNISSEUR.setForeground(new java.awt.Color(0, 102, 51));
        tabFOURNISSEUR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Fournisseur", "Raison social", "Nom", "Adresse", "Code Postal", "Ville", "Pays", "Téléphone", "Fax", "Email"
            }
        ));
        tabFOURNISSEUR.setFocusable(false);
        tabFOURNISSEUR.setGridColor(new java.awt.Color(204, 255, 255));
        tabFOURNISSEUR.setRequestFocusEnabled(false);
        tabFOURNISSEUR.setSelectionBackground(new java.awt.Color(0, 102, 51));
        tabFOURNISSEUR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabFOURNISSEURMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabFOURNISSEUR);

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTE DES FOURNISSEURS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addGap(0, 405, Short.MAX_VALUE)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(371, 371, 371))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, 720));

        btnRetour.setBackground(new java.awt.Color(255, 255, 255));
        btnRetour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRetour.setForeground(new java.awt.Color(0, 102, 51));
        btnRetour.setText("Retour");
        btnRetour.setBorderPainted(false);
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 980, 122, 34));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\phana\\Documents\\com.PokeSwing_jar_1.0-SNAPSHOT\\logo.png")); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 250));

        fond.setIcon(new javax.swing.ImageIcon("C:\\Users\\phana\\Documents\\com.PokeSwing_jar_1.0-SNAPSHOT\\FondEcranPoke1.png")); // NOI18N
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2090, 1280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMActionPerformed

    Connection con; // déclaratioon de connection 
    PreparedStatement pst; 
    
    private void tableUpdate(){
            int cpt;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/pokedb", "root","prout_KK1987"); // Demande au DriverManager (gestionnaire de manager) de récupérer et de stocker les infos dans la variable con
                    pst = con.prepareStatement("SELECT * FROM fournisseurs");
                    ResultSet rs = pst.executeQuery();
                    ResultSetMetaData rsmd = rs.getMetaData();
                    cpt = rsmd.getColumnCount();
                    DefaultTableModel dtm = (DefaultTableModel) tabFOURNISSEUR.getModel();
                    dtm.setRowCount(0);
                    
                    while(rs.next()){
                        Vector  vect = new Vector();
                        
                        for(int i = 1; i <= cpt; i++){
                            vect.add(rs.getString("IDFOUR"));
                            vect.add(rs.getString("RAISONSOCIAL"));
                            vect.add(rs.getString("NOMFOUR"));
                            vect.add(rs.getString("ADRESSEFOUR"));
                            vect.add(rs.getString("CODEPOSTALFOUR"));
                            vect.add(rs.getString("VILLEFOUR"));
                            vect.add(rs.getString("PAYSFOUR"));
                            vect.add(rs.getString("TELEPHONEFOUR"));
                            vect.add(rs.getString("FAXFOUR"));
                            vect.add(rs.getString("EMAILFOUR"));
                            
                        }
                    dtm.addRow(vect);
                    }
                            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    private void btnAjouterFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterFActionPerformed
        // Ajout fournisseur via le bouton "ajouter"
        String raisonSocialFour = txtRAISONSOCIAL.getText();
        String nomFour = txtNOM.getText();
        String adresseFour = txtADRESSE.getText();
        String codePostalFour = txtCODEPOSTAL.getText();
        String villeFour = txtVILLE.getText();
        String paysFour = txtPAYS.getText();
        String telephoneFour = txtTELEPHONE.getText();
        String faxFour = txtFAX.getText();
        String emailFour = txtEMAIL.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pokedb", "root","prout_KK1987"); // Demande au DriverManager (gestionnaire de manager) de récupérer et de stocker les informations dans la variable con
            pst = con.prepareStatement("INSERT INTO fournisseurs(RAISONSOCIAL,NOMFOUR,ADRESSEFOUR,CODEPOSTALFOUR,VILLEFOUR,PAYSFOUR,TELEPHONEFOUR,FAXFOUR,EMAILFOUR) VALUES(?,?,?,?,?,?,?,?,?)"); //appel du "statement" contenant toutes les informations
            
            pst.setString(1, raisonSocialFour);
            pst.setString(2, nomFour);
            pst.setString(3, adresseFour);
            pst.setString(4, codePostalFour);
            pst.setString(5, villeFour);
            pst.setString(6, paysFour);
            pst.setString(7, telephoneFour);
            pst.setString(8, faxFour);
            pst.setString(9, emailFour);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Données enregistrées"); // pour afficher une fenetre
            
            //Pour vider le contenu des champs après avoir ajouter un objet
            txtRAISONSOCIAL.setText("");
            txtNOM.setText("");
            txtADRESSE.setText("");
            txtCODEPOSTAL.setText("");
            txtVILLE.setText("");
            txtPAYS.setText("");
            txtTELEPHONE.setText("");
            txtFAX.setText("");
            txtEMAIL.setText("");
            
            tableUpdate();
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAjouterFActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
       
        dispose();
       
        
    }//GEN-LAST:event_btnRetourActionPerformed

    private void btnModifierFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierFActionPerformed
        
        try {
            DefaultTableModel dtm = (DefaultTableModel) tabFOURNISSEUR.getModel();
            int selectedIndex = tabFOURNISSEUR.getSelectedRow();
            
            int idFournisseur = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString()); // integer.parseInt=> converti le type en entier
            String raisonsocial = txtRAISONSOCIAL.getText();
            String nomFour = txtNOM.getText();
            String adresseFour = txtADRESSE.getText();
            String codepostalFour = txtCODEPOSTAL.getText();
            String villeFour = txtVILLE.getText();
            String paysFour = txtPAYS.getText();
            String telephoneFour = txtTELEPHONE.getText();
            String faxFour = txtFAX.getText();
            String emailFour = txtEMAIL.getText();
            
            
            Class.forName("com.mysql.cj.jdbc.Driver"); //Enregistre le driver
            con = DriverManager.getConnection("jdbc:mysql://localhost/pokedb", "root","prout_KK1987");
            pst = con.prepareStatement("update fournisseurs set RAISONSOCIAL=?, NOMFOUR=?, ADRESSEFOUR=?, CODEPOSTALFOUR=?, VILLEFOUR=?, PAYSFOUR=?, TELEPHONEFOUR=?, FAXFOUR=?, EMAILFOUR=? where IDFOUR=?");
            pst.setString(1, raisonsocial);
            pst.setString(2, nomFour);
            pst.setString(3, adresseFour);
            pst.setString(4, codepostalFour);
            pst.setString(5, villeFour);
            pst.setString(6, paysFour);
            pst.setString(7, telephoneFour);
            pst.setString(8, faxFour);
            pst.setString(9, emailFour);
            pst.setInt(10, idFournisseur); // attention Int
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Données mise à jour");
            
            txtRAISONSOCIAL.setText("");
            txtNOM.setText("");
            txtADRESSE.setText("");
            txtCODEPOSTAL.setText("");
            txtVILLE.setText("");
            txtPAYS.setText("");
            txtTELEPHONE.setText("");
            txtFAX.setText("");
            txtEMAIL.setText("");
            
            tableUpdate();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PokeDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnModifierFActionPerformed

    private void tabFOURNISSEURMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFOURNISSEURMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) tabFOURNISSEUR.getModel();
        int selectedIndex = tabFOURNISSEUR.getSelectedRow();
        
        txtRAISONSOCIAL.setText(dtm.getValueAt(selectedIndex, 1).toString()); //récupere les données dans dtm, la valeur 1 dans le champs selectionné
        txtNOM.setText(dtm.getValueAt(selectedIndex, 2).toString());
        txtADRESSE.setText(dtm.getValueAt(selectedIndex, 3).toString());
        txtCODEPOSTAL.setText(dtm.getValueAt(selectedIndex, 4).toString());
        txtVILLE.setText(dtm.getValueAt(selectedIndex, 5).toString());
        txtPAYS.setText(dtm.getValueAt(selectedIndex, 6).toString());
        txtTELEPHONE.setText(dtm.getValueAt(selectedIndex, 7).toString());
        txtFAX.setText(dtm.getValueAt(selectedIndex, 8).toString());
        txtEMAIL.setText(dtm.getValueAt(selectedIndex, 9).toString());
    }//GEN-LAST:event_tabFOURNISSEURMouseClicked

    
    /**
     * @param args the command line arguments
     */
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fournisseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterF;
    private javax.swing.JButton btnModifierF;
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnSupprimerF;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel main;
    private javax.swing.JTable tabFOURNISSEUR;
    private javax.swing.JTextField txtADRESSE;
    private javax.swing.JTextField txtCODEPOSTAL;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtFAX;
    private javax.swing.JTextField txtNOM;
    private javax.swing.JTextField txtPAYS;
    private javax.swing.JTextField txtRAISONSOCIAL;
    private javax.swing.JTextField txtTELEPHONE;
    private javax.swing.JTextField txtVILLE;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnRetour
     */
 
}
